version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfile.enUS
    ports:
      - "5000:80/tcp"
    depends_on:
      - postgres
    networks:
      - reviews

  app-ru:
    build:
      dockerfile: Dockerfile.ru
    ports:
      - "5001:80/tcp"
    depends_on:
      - postgres
      - app
    networks:
      - reviews

  postgres:
    image: postgres:latest
    ports: 
      - "5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    networks:
      - reviews
    
networks:
  reviews:
    driver: bridge

volumes:
  postgres_data:
    external: true